version: "3.8"

services:
  rdd-master:
    image: bitnami/spark:3.5.5
    container_name: rdd-spark-master
    hostname: rdd-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./apps:/opt/bitnami/spark/apps
    networks:
      - rdd-network

  rdd-worker-1:
    image: bitnami/spark:3.5.5
    container_name: rdd-worker-1
    hostname: rdd-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://rdd-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - rdd-master
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./apps:/opt/bitnami/spark/apps
    networks:
      - rdd-network

  rdd-worker-2:
    image: bitnami/spark:3.5.5
    container_name: rdd-worker-2
    hostname: rdd-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://rdd-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - rdd-master
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./apps:/opt/bitnami/spark/apps
    networks:
      - rdd-network

networks:
  rdd-network:
    driver: bridge

volumes:
  spark-data:
  spark-apps: